### ISSUE TITLE
Support for highlight current line!

### ISSUE THREAD

**Issue by endurancist** [patstockwell/vim-monokai-tasty#1]
I really like your color scheme! Are you planning on adding current line highlight in your color scheme? It would be awesome: )

**Comment by patstockwell** [comment]
Hi @endurancist, thanks for the feedback ❤️ 
I've kept the current line highlighting to a minimum as that's how it is in Sublime, which is what I was trying to emulate. You'll notice the current line number is highlighted. But not the whole line. 
You can add customised parts by adding extras in your `.vimrc` file. If you want the line highlighted, try adding the following line with the colour of your choice:
```
hi CursorLine ctermbg=186
```
This will give you what you're after I hope 😄 If you're wondering what colour 186 is, I used [this site](https://jonasjacek.github.io/colors/) to reference all my cterm colours.

**Comment by endurancist** [comment]
thanks! That's helpful!

**Comment by billyvg** [comment]
Hmm I'm not seeing the line number highlighted (and adding `hi CursorLine ctermbg=186` does nothing either).

**Comment by patstockwell** [comment]
Hi @billyvg, question reported above was about highlighting the whole line right across the window. The `hi CursorLine` relates to that.
The line number highlight is definitely configured in vim-monokai-tasty. (Check the screenshot, you should see it lit up yellow). Are you seeing the colorscheme at all? Is just the line number the problem?

**Comment by billyvg** [comment]
Yeah the colorscheme is working, the number is not being lit up yellow.

**Comment by RCMainak** [comment]
@patstockwell I'm facing the same issue. The colorscheme works fine but the line number highlight doesn't work. How can I help debug this issue. 

I've added the whole line highlight code in my .vimrc file just to check but that doesn't work as well.

Thanks for the awesome work. I'm long time sublime user with the monokai theme. You & the other contributers have done awesome job to reproduce the theme. All though there are some missing bits, I'll put those in separate issues.

**Comment by patstockwell** [comment]
Hi @RCMainak, The number highlight works for the current line when the cursorline variable is set. Try running `:set cursorline`. Thanks for the feedback, glad you like the theme! 😄
