### ISSUE TITLE
Monokai Pro variant

### ISSUE THREAD

**Issue by duhok1** [patstockwell/vim-monokai-tasty#16]
Can you make a copy of the vim version based on the updated [Monokai Pro](https://www.monokai.pro/) colors?

![6a94a056f6a649c5b30ebb3f9ffc5995704d289f](https://user-images.githubusercontent.com/46654846/55916001-14598800-5bb9-11e9-92c5-48a4ea5a9e99.png)

It is available for [Sublime](https://packagecontrol.io/packages/Theme%20-%20Monokai%20Pro)

I have extracted the color codes, but can't incorporate them well.

Thanks!

**Comment by patstockwell** [comment]
Hi @duhok1, I used monokai pro as a base when I started this theme. You can see the hex colour codes I settled on here: https://github.com/patstockwell/vim-monokai-tasty/blob/master/colors/vim-monokai-tasty.vim#L24-L29

Is there something that I missed? What do you think is different about `vim-monokai-tasty` that you want changed?

**Comment by RCMainak** [comment]
Hey @patstockwell, not sure I should put it here or create a new issue. I would like to see some enhancement for **javascript arrow functions**. Let me give you an example in the following screenshots,

Sublime Text with Monokai Pro
![Screenshot at 2019-04-15 11-44-10](https://user-images.githubusercontent.com/12175980/56111191-c1931e00-5f74-11e9-9b31-bb3c7f6ea6a6.png)

Vim with vim-monokai-tasty
![Screenshot at 2019-04-15 11-43-48](https://user-images.githubusercontent.com/12175980/56111247-ea1b1800-5f74-11e9-8b62-90bd8748d411.png)

Thanks for the great work.

**Comment by patstockwell** [comment]
Hi @RCMainak,

Thanks for taking the time to give me some feedback! From the picture, I'm guessing you're pointing out the colour of the identifier 'arrowFunc'. You've picked up on something I've been trying to fix for a while. The short answer is, I don't think I can fix this yet. If I make the variable name green, then all variable names will be green, regardless of whether they are arrow functions or not.

Unfortunately, there aren't currently and identifiers which separate variables that are arrow functions, and variables for other data types.

In VIM, the job of matching and identifying grammar from a language is done with a syntax file. It uses Regex to parse and identify different parts of the language (eg. keywords, semicolons, etc). The job of highlighting is simply to give colours to each of the syntax groups. _vim-monokai-tasty_ only takes exisiting highlight groups and gives them a colour. You'll notice in the README that I recommend extra plugins. Some of these are syntax files which identify more parts of the language for us. Unfortunately, nobody has figured out how to differentiate between an arrow function variable and normal variables.

If you can come up with a Regular expression that differentiates variables, I'd love to incorporate it!
