### ISSUE TITLE
Error when starting vim: Cannot find color scheme 'tastySublime'

### ISSUE THREAD

**Issue by tanc** [patstockwell/vim-monokai-tasty#2]
After installing your colour scheme (which is very nice!), when firing up neovim I'm seeing this error:
```
Error detected while processing /usr/share/nvim/runtime/syntax/synload.vim:
line   19:
E185: Cannot find color scheme 'tastySublime'
```

**Comment by patstockwell** [comment]
Hi @tanc thanks for the feedback 🎉  
I just noticed this error this morning. I've updated the name _in_ the file to match the name _of_ the file. Both should now be `vim-monokai-tasty`.
Try updating the plugin. Either remove it and start fresh, or If you use Plug, then the command `PlugUpdate` should do it. (Warning - this will update all your plugins).
Please let me know if you have other problems

**Comment by xxzozaxx** [comment]
Hi @patstockwell,

Sorry but it seem like the issue are not solved yet.
```
Error detected while processing /home/master/.config/nvim/init.vim:
line   51:
E185: Cannot find color scheme 'vim-monokai-tasty'
```
I get this also when I open NeoVim.

**Comment by patstockwell** [comment]
Ah cool, well at least we know it works 😄 As for why you have to run `colorscheme vim-monokai-tasty` after you start vim, that sounds like things happening out of order. In your `.vimrc`, do you have your `colorscheme` declaration before your plugins?
I use neovim too, so I don't think that should be a problem 🌮

**Comment by xxzozaxx** [comment]
Oppps.

I feel like dump now T_T. I don't know why I though vim don't interpret the config file. I just though it do it as magic so I put it any way and vim will understand.

Thanks @patstockwell  so much for help and for your awesome theme. it really the TRUE monokai
