### ISSUE TITLE
listchar background issue

### ISSUE THREAD

**Issue by albertorestifo** [patstockwell/vim-monokai-tasty#23]
When showing invisible characters, the background of the `listchar` doesn't match the background of the editor.

To reproduce:

```
set list
set listchars=tab:»\ ,extends:›,precedes:‹,nbsp:·,trail:·,space:·
```

<img width="821" alt="image" src="https://user-images.githubusercontent.com/1037048/67187787-46ab3400-f3eb-11e9-8519-ee6292dbaa9f.png">

**Comment by patstockwell** [comment]
Hmmm, thanks for taking the time to write this up. I've tried to reproduce the bug but can't seem to make it look like what you've captured in the screen shot.

<img width="486" alt="Screen Shot 2019-11-16 at 2 20 19 pm" src="https://user-images.githubusercontent.com/14284552/68987258-44b68280-087c-11ea-8edb-773b25548f33.png">

 I think `listchars` is highlighted by the `Whitespace` highlight group in vim. _vim-monokai-tasty_ sets `Whitespace` to have a [darkgrey foreground, and nothing in the background](https://github.com/patstockwell/vim-monokai-tasty/blob/master/colors/vim-monokai-tasty.vim#L92). So your `listchar`s should be showing the with a transparent background.

Do you have a custom highlight rule somewhere in your _.vimrc_ that is setting the background to light grey?

Try running the following commands and see if you get any changes
```vim
:set termguicolors
:hi Whitespace guibg='none'
```
Let me know how you go.

**Comment by patstockwell** [comment]
@albertorestifo if you're still having trouble, reach out to me and let me know.
