### ISSUE TITLE
Theme for tmux

### ISSUE THREAD

**Issue by maharjanaman** [patstockwell/vim-monokai-tasty#24]
Is there a theme for tmux same as lightline?

**Comment by patstockwell** [comment]
Ah don't have a tmux theme. Would happily take a PR if you have time though!

**Comment by maharjanaman** [comment]
Wish I new more about this theming. But I'll give it a shot.
Also is it possible to have lighter contrast for [zsh-autosuggestions](https://github.com/zsh-users/zsh-autosuggestions)?

**Comment by patstockwell** [comment]
I think zsh is outside the scope of this vim plugin.
