### ISSUE TITLE
red and green for git?

### ISSUE THREAD

**Issue by nqthqn** [patstockwell/vim-monokai-tasty#25]
I noticed adding and removing stuff is in purple and blue - could this be changed to use green and red?

<img width="457" alt="image" src="https://user-images.githubusercontent.com/857356/78113277-5aa08c00-73b4-11ea-86c3-5015a8581cc4.png">

**Comment by patstockwell** [comment]
Great suggestion. Done!

<img width="588" alt="Screen Shot 2020-04-04 at 10 20 34 am" src="https://user-images.githubusercontent.com/14284552/78412173-23ed9e80-765e-11ea-9f5a-0b214c048aef.png">
