### ISSUE TITLE
Cannot allocate color none

### ISSUE THREAD

**Issue by harababurel** [patstockwell/vim-monokai-tasty#3]
Installed the colorscheme by including `Plug 'patstockwell/vim-monokai-tasty'` along with my other plugins, running `:PlugInstall` and setting `:colorscheme vim-monokai-tasty`. It results in the following errors (around ~100 lines):

```
Error detected while processing function Highlight:
line    1:
E254: Cannot allocate color none
E254: Cannot allocate color none
E254: Cannot allocate color none
...
E254: Cannot allocate color none
```

Any idea why this is happening?

**Comment by mellery451** [comment]
same issue here - vim 8.1 on macos installed via homebrew.

**Comment by harababurel** [comment]
Managed to fix this by changing `vim-monokai-tasty.vim:45` from
```
let s:none = { "cterm": "none", "gui": "none" }
```
to
```
let s:none = { "cterm": "NONE", "gui": "NONE" }
```
You might also have to change line 21 (`let s:italic = { "cterm": "none", "gui": "none" }`) if you use the italic feature. I will create a pull request to fix this upstream.

**Comment by scottwater** [comment]
Same issue here and @harababurel fork fixes it for me as well.

**Comment by patstockwell** [comment]
Thanks for taking the time to create a PR 👍 
Merged.
