### ISSUE TITLE
Airline theme

### ISSUE THREAD

**Issue by Sebastian-Nielsen** [patstockwell/vim-monokai-tasty#31]
I set my airline_theme to monokai_tasty, though my statusline looks very different from [the one displayed in the readme](https://github.com/patstockwell/vim-monokai-tasty/blob/master/images/example_vim_and_markdown.png?raw=true). 
Why is that? How do I make my statusline look like the one in [the picture](https://github.com/patstockwell/vim-monokai-tasty/blob/master/images/example_vim_and_markdown.png?raw=true)

![image](https://user-images.githubusercontent.com/34586104/109433776-6fe1c880-7a12-11eb-92ed-c76967c881f4.png)

**Comment by patstockwell** [comment]
HI @Sebastian-Nielsen, You're talking about the triangle-shaped separators? This is an airline feature. Airline uses particular font symbols as section separators. You will need to install a _powerline font_. Check out the airline docs where they talk about how you can configure a powerline font! See here -> https://github.com/vim-airline/vim-airline#integrating-with-powerline-fonts

**Comment by Sebastian-Nielsen** [comment]
@patstockwell 
Thank you for your reply. The thing is I already did that! Look: 

![image](https://user-images.githubusercontent.com/34586104/111154262-50f74080-8593-11eb-8bd0-12e5d00ce4ae.png)

Why is my statusline still so ... ugly? And not like [it is supposed to look](https://raw.githubusercontent.com/patstockwell/vim-monokai-tasty/master/images/example_vim_and_markdown.png).
