### ISSUE TITLE
Add support for nvim-treesitter highlight groups

### ISSUE THREAD

**Issue by RobertBuhren** [patstockwell/vim-monokai-tasty#35]
Hi,
thanks for this awesome colorscheme, I have been using it for quite some time now. I recently started using neovim's treesitter syntax highlighting [1]. 
I was wondering whether you could add support for the highlight groups that are defined in [2].

Regards,
Robert
[1] https://github.com/nvim-treesitter/nvim-treesitter
[2] https://github.com/nvim-treesitter/nvim-treesitter/blob/master/doc/nvim-treesitter.txt#L431

**Comment by patstockwell** [comment]
Thanks for opening an issue! Looking into it.

**Comment by patstockwell** [comment]
Hi @RobertBuhren , As I'm a TypeScript developer, I started with some TS highlights. See this commit -> 1e2b0a7a2e7c098205cb3c3940f455543970fcb1

The basic mappings exist, so you will get highlighting with Treesitter regardless, however, it's a pretty huge task to add colours for all languages. Each language will require tweaks by adding a prefixed name. I'll continue adding Treesitter definitions in future as I update for various languages.

Closing the issue for now. Feel free to open another if there is a specific language or piece of syntax that doesn't make sense for you.

**Comment by Nequo** [comment]
Note that there are generic highlight groups documented here: https://github.com/nvim-treesitter/nvim-treesitter/blob/master/doc/nvim-treesitter.txt#L480.
These would apply to all languages and as far as I know you would use the language specific groups to override anything that does not look right after inheritance.

**Comment by polirritmico** [comment]
This are my modifications for Python that I made using the Treesitter highlight groups. Maybe it could be useful: https://gist.github.com/polirritmico/97f784766305eaee5ad916d6444659c2

Sorry if this is not the correct place to post this.
Thanks!

**Comment by patstockwell** [comment]
I've added more tree sitter support (thanks @polirritmico for the Python config, that's been added!)
All languages are supported by default linking, but specific styling has been added now for:
* TypeScript
* Scala
* Python

Feel free to contribute more if you require it!
