### ISSUE TITLE
Transparent background for popup windows

### ISSUE THREAD

**Issue by polirritmico** [patstockwell/vim-monokai-tasty#42]
Hi. I'm having troubles getting a transparent background with the latest commits on non focused windows or around popup windows.

This was the behavior with telescope before, at 56b6d710cecdbeb57dda592d02d68be389ffcc36 :
![Screenshot_20221124_155233](https://user-images.githubusercontent.com/24460484/203850540-304df210-30e8-4969-a8be-3f23928fd3ed.png)

But after the latest commits I couldn't get the same results:
![Screenshot_20221124_155121](https://user-images.githubusercontent.com/24460484/203851772-c31e1887-e3b3-479f-b25d-effb9f3c870e.png)

What setting I'm missing?

My config:

```lua
-- THEME --
vim.g.vim_monokai_tasty_italic = 1  -- Allow italics. ¡Set before coloscheme!
api.nvim_command("colorscheme vim-monokai-tasty")
api.nvim_create_autocmd({"ColorScheme"}, {
    pattern = "*",
    callback = function()
        api.nvim_set_hl( 0, "Normal", {
            ctermbg=NONE, guibg=NONE, fg="#ffffff"})
        end})

-- COLORS --
opt.syntax = "ON"
opt.termguicolors = true
opt.background=dark
opt.cursorline = true
api.nvim_set_hl(0,
    "Cursorline",
    { guibg=NONE })
opt.hlsearch = false
```

Thanks in advance!

**Comment by patstockwell** [comment]
Thanks for reporting this! In this commit - bcbfda62435d9ad7979fe9fb7769b23eb40338a7 - I added a highlight for the non current window which reduces the contrast for all except the active window (where you cursor is). The idea is to make your current window stand out a little more.
But for you, using telescope, the narrow `Find Files` is the active "window", making everything else take on the muted tint of the inactive window.

I've now moved this styling behind a config flag. So those who want it can enable it. See this commit - 82ce4cdd82b193cc9e02403db4d01d46afe18bbd - hopefully this fixes your issue!

Let me know ☺️

**Comment by polirritmico** [comment]
It works without any problem on my system
Thanks!
