### ISSUE TITLE
W18: Invalid character in group name

### ISSUE THREAD

**Issue by alejandrohagan** [patstockwell/vim-monokai-tasty#43]
hi!

after following the instructions I get the following error "W18: Invalid character in group name" however it appears the colorscheme is working.

When I delete the colorscheme  line the error goes away

Any thoughts on how to fix?

`colorscheme vim-monokai-tasty                       " Enable monokai theme.`

**Comment by pat-stockwell** [comment]
Thanks! I've added tree sitter support, but I'm not wrapping it in a check for neovim. I'll take a look and try and reproduce this in regular vim.

What version of Vim/Neovim are you using?

**Comment by patstockwell** [comment]
Ok I was able to reproduce the issue when starting with Vim (I use neovim). I've pushed a change which wraps the newer highlight rules in a check for `nvim` (these rules use the invalid character). This removes the error. 🎉 

If you're on neovim already, and you're getting an error, let me know which version you're using an I'll add that version number to the condition as well.

Thanks for reporting!

**Comment by patstockwell** [comment]
https://github.com/patstockwell/vim-monokai-tasty/commit/5facd3847637774b62abace015ff4ad34a1632ea

**Comment by alejandrohagan** [comment]
hi! sorry that I missed your replies and thanks for fixing!

The nvim version that I am using is NVIM v.0.7.2

**Comment by patstockwell** [comment]
Ah ok, if you got errors on version `7.x`, it looks like I'll have to add a condition which checks for neovim 8 or higher.

**Comment by patstockwell** [comment]
Updated again. Let me know if this fixed your problem.

**Comment by alejandrohagan** [comment]
hi -- its stranger -- I believe the color scheme works (eg my color scheme has changed) however I still get the same error printer 20 times.
