### ISSUE TITLE
airline: Could not resolve airline theme "monokai_tasty". Themes have been migrated to github.com/vim-airline/vim-airline-themes.

### ISSUE THREAD

**Issue by mellery451** [patstockwell/vim-monokai-tasty#7]
airline doesn't seem to find the theme...is there more config required beyond just `let g:airline_theme='monokai_tasty' ` ?  Nice scheme - thanks.

**Comment by patstockwell** [comment]
Hi @mellery451, the `let` statement you have should be enough. You’re right that airline themes have moved. This theme isn’t hosted with theirs, it’s bundled in this plugin, so you won’t need any theme extra dependencies from github.com/vim-airline/vim-airline-themes
Does the vim colorscheme work or are you only using the airline theme?

**Comment by patstockwell** [comment]
Does the `monokai_tasty` Airline theme show up after vim starts? Try:
```
:AirlineTheme <Tab>
```
And then tab through the list of available themes to search for it.

**Comment by mellery451** [comment]
I'm using this vim colorscheme also and was just trying the airline theme, but I get this error when starting with `g:airline_theme='monokai_tasty'`.   Yes, it does show up in the `AirlineTheme` list -- I get this error if I select it:

```
E121: Undefined variable: g:airline#themes#monokai_tasty#palette
```

**Comment by mellery451** [comment]
I use homebrew vim (8.1), but I just tried with homebrew nvim as well and got the same error.

I think I see the issue:  https://github.com/patstockwell/vim-monokai-tasty/blob/master/autoload/airline/themes/monokai_tasty.vim#L93
(what if you don't use ctrl-p? I don't...)

**Comment by patstockwell** [comment]
Ah that's it! Great I'll make a tweak now. Great spotting 🎉

**Comment by patstockwell** [comment]
Fixed! I've tested this by removing ctrlp and verifying the bug. Then checking the fix works too.
I'll close this issue. Please let me know if you're still having trouble. Thanks for the great feedback.
🌮

**Comment by mellery451** [comment]
confirmed - works great now.
